# Generated by Django 5.1.3 on 2024-11-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('score1', models.CharField(max_length=10)),
                ('score2', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('court', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participantID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('record', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('teamSize', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'unique_together': {('match', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(through='api.MatchParticipant', to='api.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='teamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournamentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to='api.user'),
        ),
        migrations.AddField(
            model_name='participant',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.user'),
        ),
    ]
