# Generated by Django 5.1.3 on 2025-01-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_enddate_match_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
