# Generated by Django 5.1.3 on 2025-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_tournament_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="status",
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_teams",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="show_email",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="show_phone",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
