# Generated by Django 5.1.3 on 2025-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="match",
            name="seed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="invite_link",
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="private",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
