# Generated by Django 5.1.3 on 2025-02-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_match_round_match_seed_tournament_invite_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="max_teams",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="team_size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
