# Generated by Django 5.1.3 on 2025-02-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="password",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
