# Generated by Django 5.1.3 on 2025-02-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_tournament_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="password",
            field=models.TextField(null=True),
        ),
    ]
