# Generated by Django 5.1.3 on 2025-02-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_tournament_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="invite_link",
            field=models.UUIDField(null=True),
        ),
    ]
