# Generated by Django 5.1.3 on 2025-02-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_private_tournament_isprivate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="isPrivate",
            new_name="is_private",
        ),
        migrations.AddField(
            model_name="team",
            name="invite_link",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="is_private",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="password",
            field=models.TextField(null=True),
        ),
    ]
