# Generated by Django 5.1.3 on 2025-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_rename_isprivate_tournament_is_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default="bd8fe8fa-0385-4841-9c2f-4bae086bc36b"),
            preserve_default=False,
        ),
    ]
