# Generated by Django 5.1.3 on 2025-02-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
