# Generated by Django 5.1.3 on 2025-02-20 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_team_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="invite_link",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="invite_link",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
