# Generated by Django 5.1.3 on 2025-02-20 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_team_invite_link_alter_tournament_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_by_uuid",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
            preserve_default=False,
        ),
    ]
