# Generated by Django 5.1.3 on 2025-02-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_team_created_by_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="record",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
