# Generated by Django 5.1.3 on 2025-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_team_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="record",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
