# Generated by Django 5.1.4 on 2025-02-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tournament_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
    ]
