# Generated by Django 5.1.4 on 2025-02-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_tournament_winner'),
        ('api', '0021_alter_team_record'),
    ]

    operations = [
    ]
