# Generated by Django 5.1.4 on 2025-02-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20250228_0001'),
        ('api', '0022_merge_20250228_0146'),
    ]

    operations = [
    ]
