# Generated by Django 5.1.4 on 2025-04-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_match_bracket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament_losses',
            field=models.IntegerField(default=0),
        ),
    ]
