# Generated by Django 5.1.4 on 2025-04-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_team_eliminated_team_tournament_losses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='eliminated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament_losses',
        ),
    ]
