# Generated by Django 5.1.3 on 2025-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_team_eliminated_remove_team_tournament_losses"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="verified",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
