# Generated by Django 5.1.3 on 2025-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_match_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_phase',
            field=models.IntegerField(default=1),
        ),
    ]
